### ISSUE TITLE
Crash when writing to invalid destination directory [was File creation on main thread?]

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/dfmodules#17]
I just crashed the minidaqapp with the following error:
(Why the file creation failed is known, that's not the topic of this issue)

`
2021-Jan-21 14:07:36,798 LOG [dunedaq::trigemu::TriggerDecisionEmulator::do_resume(...) at /scratch/dingpf/dunedaq-v2.2.0-prep/workdir/sourcecode/trigemu/plugins/TriggerDecisionEmulator.cpp:134] ******* Triggers RESUMED! *********
2021-Jan-21 14:07:36,798 INFO [stdinCommandFacility::completionCallback(...) at /scratch/dingpf/dunedaq-v2.2.0-prep/workdir/sourcecode/cmdlib/plugins/stdinCommandFacility.cpp:91] Command execution resulted with: OK
2021-Jan-21 14:07:37,265 DEBUG_0 [dunedaq::trigemu::TriggerDecisionEmulator::send_trigger_decisions(...) at /scratch/dingpf/dunedaq-v2.2.0-prep/workdir/sourcecode/trigemu/plugins/TriggerDecisionEmulator.cpp:200] At timestamp 79759096250428168, pushing a decision with triggernumber 1 timestamp 79759096150000000 number of links 10
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: /scratch/workspace/hep_hpc_toolkit-all/MQUAL/NO_MPI/QUAL/e19/label1/swarm/label2/SLF7/build/hdf5/v1_12_0a/source/hdf5-1.12.0/src/H5F.c line 705 in H5Fcreate(): unable to create file
    major: File accessibility
`

Did I understood properly that files are created on the first event? And it's done in the main working thread? 

As a first and most important issue with this, is that file open/creation should happen on COnfigure and should check that the directory is there and writeable to. 

(I would also detach this particular File handling mechanism from the main worker thread, as this operation can have substantial latency spikes on different hardware/kernel configurations.)

**Comment by bieryAtFnal** [comment]
This will need some discussion.
For example, files cannot be created at Configure time if we need to put the run number in the filename.  We don't get the run number until the Start command.

**Comment by roland-sipos** [comment]
Ah I see. And also sorry for over-complicating this issue with the "main thread".

I think as a first thing to do in order to mitigate this issue is, to make a "touch file" test on the destination directory during Configure.
