### ISSUE TITLE
Lost TriggerRecord in 3ru_1df test with N22-05-22 nightly?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/dfmodules#177]
When I run the following test with the N22-05-022 Spack nightly build, 

```
daqconf_multiru_gen -d ./frames.bin -o . -s 10 -n 3 -b 1000 -a 1000 --latency-buffer-size 200000 --host-ru localhost --host-ru localhost --host-ru localhost --region-id 0 --region-id 1 --region-id 2 mdapp_3ru_1df
curl -o frames.bin -O https://cernbox.cern.ch/index.php/s/7qNnuxD8igDOVJT/download
nanorc mdapp_3ru_1df/ boot ${USER}_test init conf start 201 wait 20 stop wait 3 scrap terminate
```

I see the following error in the DF App log:

```
log_dataflow0_3339.txt:2022-May-22 07:10:53,110 ERROR [bool dunedaq::dfmodules::TriggerRecordBuilder::send_trigger_record(const dunedaq::dfmodules::TriggerId&, std::atomic<bool>&) at /home/biery/dunedaq/22MayDevTest/sourcecode/dfmodules/plugins/TriggerRecordBuilder.cpp:685] trigger ID 20-0/201 could not be sent to writing and it's lost
```

**Comment by philiprodrigues** [comment]
I'm able to reproduce this issue. There are at least two problems, if I'm understanding correctly. First, `TriggerRecordBuilder` has this:

https://github.com/DUNE-DAQ/dfmodules/blob/cc05877fd75d5d4a4e493529b83b1750ed13c2b3/plugins/TriggerRecordBuilder.cpp#L670-L680

which won't even attempt the send if it's called after the `running` flag is set to false. I assume a `do {...} while (...);` loop is intended.

The problem upstream of that is that the TC for that TR is not being returned, which must be some problem in `trigger` or `readoutlibs`. I recently wrote code to handle exactly this case, so I'm not sure what's up. Investigating.

**Comment by mroda88** [comment]
@philiprodrigues you are correct, that should definitely be a `do while` loop. I can fix it quickly if you want to work on the readoutlib side.

**Comment by philiprodrigues** [comment]
Two other problems contributed to this issue:
1. I made a mistake in handling waiting data requests at run stop in `readoutlibs`. This is fixed by https://github.com/DUNE-DAQ/readoutlibs/pull/28
2. The logic in `daqconf` to determine the start order of apps had bitrotted. This is fixed by https://github.com/DUNE-DAQ/daqconf/pull/70

With these two PRs, I no longer saw the missing fragment at the end of run.

**Comment by bieryAtFnal** [comment]
I believe all of the issues described in this Issue have been addressed.
