### ISSUE TITLE
FileWriter module - Dry-run feature?

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/dfmodules#18]
After a discussion with Adam, we were thinking about adding a dry-run mode to the FileWriter module, which carries out every communication with other connected modules, but NOT doing any file I/O. 

This would help a lot with high rate tests, as we can completely decouple the disk I/O + HDF5 writing footprint from the overall system perf tests.

**Comment by bieryAtFnal** [comment]
This feature request is covered as one of the enhancements in Issue #21.  

I will submit a PR for Issue #21 soon, so hopefully this feature will become available soon.

In the meantime, I'm going to close this Issue since it is a duplication of what is mentioned in Issue #21.
