### ISSUE TITLE
TRB very inefficient with exceptions

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/dfmodules#186]
The loop in the TRB is controlled by a number of receive calls that have 0 timeout. 
Due to what has been discussed yesterday, this is far from optimal. 
Since we now have dedicated methods to solve this, we should use them

**Comment by dingp** [comment]
@mroda88 I linked PR #187 to this issue. Is this issue resolved with the merged PR?

**Comment by mroda88** [comment]
Yes!
