### ISSUE TITLE
A couple of minor changes to what we see in the output HDF5 file

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/dfmodules#24]
At the moment, we are labeling the sub-detector Group in the HDF5 as "FELIX", when in fact, we should be labeling that "TPC".  It would be nice to change the HDF5DataWriter to output the "TPC" name.  There are other places where the "FELIX" name is also used, e.g. in unit tests.  Those are less important to change, but maybe we change those also, for completeness.

Another minor point is the APA number that we get when using the FakeDataProd module.  It seems like we get an APA number of 1 with it, whereas we get an APA number of zero when using the full v1.0 minidaqapp.  It would be nice to investigate if/why these are different and get the testapp_noreadout system to match the minidaq-app system.

Just a couple of minor things that I don't want to forget...

**Comment by bieryAtFnal** [comment]
I made the changes for this Issue on branch feature/Issue24_MinorHDF5Changes.  That branch was based on the one for Issue34.  Once that branch is merged, I'll create a PR for this one.

**Comment by glehmannmiotto** [comment]
I think it would be nice to introduce a lookup table with a clear association:
FragmentHeader. m_fragment_type -> Group name
This could then be used in the code and controlled from a single place.

**Comment by bieryAtFnal** [comment]
I agree that it would be good to create a mapping from Fragment type to HDF5 Group name.  I will create an Issue in the minidaqapp repo for that, since it will affect multiple repositories.

In the meantime, I hope that we can get these simple changes approved and merged, so I will create a Pull Request in this repo for them.
