### ISSUE TITLE
Configuration parameters with constrains in moo ?

### ISSUE THREAD

**Issue by carloschavez** [DUNE-DAQ/dfmodules#29]
When testing some of our data writing functionality, an issue came up about the need of using configurations parameters with constraints in order to avoid setting values that do not make sense in the configuration.

Is this functionality available in moo ?  
It would be great if this is the case.

As an example, if we want to make sure that a parameter holds values within certain range of values (1,100000) ,  can this be done in moo ?

**Comment by brettviren** [comment]
Hi @carloschavez.  

Right now the answer is "yes and no" but it is certainly valid to want the answer to be "yes".  moo allows numeric constraints to be specified but then goes and totally ignores them.

I made a moo issue with details.

https://github.com/brettviren/moo/issues/17

Once that is closed maybe this ticket can be closed as soon as someone updates the schema in `dfmodules` to set some constraints.

**Comment by brettviren** [comment]
FYI, @carloschavez there is now support in moo for numeric constraints.

Some docs are added to the "number" subsection of https://brettviren.github.io/moo/oschema.html#atomic
