### ISSUE TITLE
Error Handling 

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/dfmodules#30]
I'm opening this issue to keep track of the improvements we can implement for better error handling

### Data Writer
- [x] There is a `throw` in `do_work`, it should be substituted with a `fatal`. 
- [x] `do_init` and `do_conf` can throw. It is worth noting here that `make_data_store` can throw. 
- [x] the call to write https://github.com/DUNE-DAQ/dfmodules/blob/03e0dc38526734515846d9de86fd2e583dbbddae/plugins/DataWriter.cpp#L258    should be inside a try-catch loop as in principle other DataStores could throw. This call should also catch standard exceptions, not only ers.  

### HDF5DataStore
- [x] The catch block https://github.com/DUNE-DAQ/dfmodules/blob/03e0dc38526734515846d9de86fd2e583dbbddae/plugins/HDF5DataStore.hpp#L204-L208 can be simplified and made more consistent: we should only catch `HighFive` exception and rethrow something that can be cought by the DataWriter. 

### Fragment Receiever (clean)
* Here is the possibility that booking memory fails to be allocated if not enough resources are available in the machine but we agreed it is not worth guarding against this.

### KeyedDataBlock
- [x] following the discussion from yesterday, we could define the constructor as `noexcept`

**Comment by glehmannmiotto** [comment]
About HDF5DataStore, I think that that library should take care of catching any std exceptions and creating/throwing ERS issues, allowing the higher levels of code to rely on the fact that catching ERS issues is sufficient.

**Comment by philiprodrigues** [comment]
Re handling `std::bad_alloc`, I had thought that it was pointless because `bad_alloc` is only thrown when all is lost, but this article suggests that's not the case:

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1404r1.html

In particular, `bad_alloc` is likely to be thrown when requesting a stupendously large memory allocation, when smaller allocations (in the catch block, say) would still succeed.

I don't know what this implies for the specific case of handling `std::bad_alloc` in `FragmentReceiver`, but hopefully the article is useful in thinking it through.

**Comment by mroda88** [comment]
Hi Phil, this is a nice input, thanks. I have two comments following the article you suggested. One is for the specific case of `std::bad_alloc` in our application, the other is related to the desired non-crashing behaviour desired from our applications. I think they are connected topics. 

About the `std::bad_alloc`. The memory allocations in `FragmentReceiver` are not contiguous, as the _books_ are `std::maps`, not vectors. And since we store either `TriggerDecisions` or pointers, the local memory allocation is small and there are already mechanisms to notify that the fragments are piling up. So my feeling is that adding a `try-catch` block here would only reduce readability. 
There is, however, a place in the readout app that could cause a large memory allocation in one single request: it's the creation of the fragments, in the readout part. There we might want to guard the code against a bad allocation. 

The end of the paper tries to provide nice hints about this issue here https://github.com/DUNE-DAQ/appfwk/issues/133 . Or rather it made me realise that there are always things we might not be able to guard against. A bad allocation is one of these cases. I think the bad allocation is a reason for which we might want to rethrow.
