### ISSUE TITLE
dfmodulesConfig.cmake.in has a bug

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/dfmodules#33]
Alessandro noticed that `dfmodulesConfig.cmake.in` has the following line:
```
add_library(appfwk::appfwk ALIAS appfwk)
```
which suggests that `appfwkConfig.cmake` got copied into dfmodules and then got edited. What this means is that if you have a work area with a dfmodules repo and a repo which depends on dfmodules, you'll get an error. 

To fix this: the correct procedure to set up a package so it can be included as a dependency via `find_package(yourpackagename)` is described on the wiki, https://github.com/DUNE-DAQ/appfwk/wiki/Creating-a-new-package-under-v2.2.0, under "Installing your project as a local package".

**Comment by bieryAtFnal** [comment]
I believe that this Issue can be closed thanks to Pull Request #37.
