### ISSUE TITLE
Names of HDF5 files in v5 minidaq system noticeably different than in v4

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/dfmodules#373]
I'm not sure if this is the correct repository for filing this Issue, but I'll start here and be willing to move it, if needed.

Basically, my concern is that the filenames for raw data and TP stream HDF5 files from a simple minidaq test show a very different pattern than what we used previously, *and* the new pattern seems to have some undesirable features.

Here are three sample files from a v5 minidaq test, two produced by TRB/DataWriters and one produced by the TPStreamWriter:
```
test_raw_run000101_0000_default_20240814T164113.hdf5
test_raw_run000101_0000_default_20240814T164114.hdf5
test_raw_run000101_0000_default_tp_store_conf_20240814T164114.hdf5
```

Here are three sample files from a corresponding v4 minidaq test.
```
swtest_run000921_0000_dataflow0_datawriter_0_20240814T172121.hdf5
swtest_run000921_0000_dataflow1_datawriter_0_20240814T172121.hdf5
tpstream_run000921_0000_tpwriter_tpswriter_20240814T172122.hdf5
```

For reference, here are some sample filenames from NP04 running:
```
/data4/np04hd_raw_run028694_0009_dataflow6_datawriter_0_20240814T172224.hdf5
/data0/np04hd_tp_run028694_0018_tpwriter_tpswriter_20240814T171951.hdf5
```

My concerns about the v5 filenames include the following:

1.  The two TRB/DataWriter files are only distinguished by the timestamp.  Recall that this timestamp is only included as a safety check to avoid duplicate filenames, so we shouldn't be counting on it as the first level of defense for unique filenames.
2. The TPStream filename has a prefix of "test_raw" instead of "test_tp".
3. The TPStream filename has odd text in it.  What does "tp_store_conf" mean, and why is it in the filename?
4. There doesn't seem to be an indication of the process name in any of the filenames.  Maybe this is not important, but it is part of how filenames are distinguished in v4.x running.

**Comment by bieryAtFnal** [comment]
Here are step-by-step instructions for running a v5 minidaq system that will produce filenames similar to the ones mentioned above:

```
YMD_STRING=`date '+%y%m%d'`
DATE_PREFIX=`date '+%d%b'`
TIME_SUFFIX=`date '+%H%M'`

source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
setup_dbt latest_v5
dbt-create -n NFD_DEV_${YMD_STRING}_A9 ${DATE_PREFIX}FDv5Test${TIME_SUFFIX}
cd ${DATE_PREFIX}FDv5Test${TIME_SUFFIX}/sourcecode

git clone https://github.com/DUNE-DAQ/appmodel.git -b develop
cd ..

dbt-workarea-env
dbt-build -j 12
dbt-workarea-env

mkdir rundir
cd rundir

echo ""
echo "# Execute the following commands by hand:"
echo ""
echo "drunc-unified-shell ssh-standalone"
echo ""
echo "# within drunc..."
echo "boot test/config/test-session.data.xml test-session"
echo "fsm conf"
echo "fsm start run_number 101"
echo "fsm enable_triggers"
echo "# wait for 10 seconds or so"
echo "fsm disable_triggers"
echo "fsm drain_dataflow"
echo "fsm stop_trigger_sources"
echo "fsm stop"
echo "fsm scrap"
echo "quit"

echo "ls -alF *.hdf5"

echo "egrep 'ERROR|WARNING' log_*"
```

**Comment by glehmannmiotto** [comment]
The issue comes from this line:
https://github.com/DUNE-DAQ/dfmodules/blob/eab8ce9c25b4440be096b11db6644236360273d5/plugins/HDF5DataStore.hpp#L127C5-L127C24

The m_writer_identifier in the old configuration system was generated automatically for each writer to <application_name>_<module_name>. In v5 the name taken is the name of the DataStoreConf object.

**Comment by bieryAtFnal** [comment]
Thanks for looking into this.  I'll take a look at PR #374 soon.

Independent of that, I created a `kbiery/hdf5_filename_prefix_ideas` branch in the `appmodel` repo which has some possible changes to fix the "raw" -> "tp" file_type_prefix for TPStream files, and try out a "swtest" operational environment.  I'll ask about that when we have a chance.
