### ISSUE TITLE
Crash if no fragments available for TriggerDecision

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/dfmodules#66]
This line doesn't check that the `find()` returns a valid iterator, so can cause a crash at stop time:

https://github.com/DUNE-DAQ/dfmodules/blob/9bf1cdbd00e1827e78f5585932cff4d11ac61a82/plugins/FragmentReceiver.cpp#L375

To reproduce:

```
python -m nanorc.mdapp_multiproc_gen -c 10 -n 3 -s 10 -t 20 3proc
# Issue trigger requests way early, so the data isn't in the buffers yet
sed -i -e 's,"trigger_delay_ticks": 5000000,"trigger_delay_ticks": -50000000,' 3proc/data/trgemu_conf.json
nanorc.py 3proc boot init conf start 1 resume wait 11 stop scrap terminate
```

**Comment by mroda88** [comment]
Hi @philiprodrigues, I checked, this is not happening in the TRBuilder as the container is the same for fragments and trigger decision. So I'll close this issue.
