### ISSUE TITLE
hdf5_dump.py -c doesn't print out TR number, but it would be great if it did

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/dfmodules#68]
I noticed that when I run the hdf5_dump.py script and use the "-c" flag (check fragments), the "Trigger record number" that is displayed is not actually the TR number.  Instead, it seems to be some sort of internal index.

I would like to request one of the following:

- this gets changed so that the TR number does  get printed out, or
- the TR  number is added to the printout and the text that explains what "i" is gets changed to correctly reflect what it is.

For reference, here are outputs that show the discrepancy:

(dbt-pyvenv) [biery@mu2edaq13 rundir]$ hdf5_dump.py -c -f swtest_run42830909_0001_biery_20210428T141000.hdf5
Reading file swtest_run42830909_0001_biery_20210428T141000.hdf5
---------------------Column Definitions---------------------
i:           Trigger record number;
N_frag_exp:  expected no. of fragments stored in header;
N_frag_act:  no. of fragments written in trigger record;
N_diff:      N_frag_act - N_frag_exp
---------------------Column Definitions---------------------
    i       N_frag_exp     N_frag_act     N_diff  
    0            2              2           0     
    1            2              2           0     
    2            2              2           0     
    3            2              2           0     
    4            2              2           0     
    5            2              2           0     
    6            2              2           0     
    7            2              2           0     
    8            2              2           0     
    9            2              2           0     
    10           2              2           0     
    11           2              2           0     
    12           2              2           0     
    13           2              2           0     
    14           2              2           0     
    15           2              2           0     
    16           2              2           0     
    17           2              2           0     
    18           2              2           0     
    19           2              2           0     
    20           2              2           0     
    21           2              2           0     
    22           2              2           0     
    23           2              2           0     
    24           2              2           0     
    25           2              2           0     
    26           2              2           0     
    27           2              2           0     
    28           2              2           0     
    29           2              2           0     
    30           2              2           0     
    31           2              2           0     
    32           2              2           0     
    33           2              2           0     
    34           2              2           0     
    35           2              2           0     
    36           2              2           0     
    37           2              2           0     
    38           2              2           0     
    39           2              2           0     
    40           2              2           0     
    41           2              2           0     
    42           2              2           0     
    43           2              2           0     
    44           2              2           0     
    45           2              2           0     
    46           2              2           0     
    47           2              2           0     
    48           2              2           0     
    49           2              2           0     
    50           2              2           0     
    51           2              2           0     
    52           2              2           0     
    53           2              2           0     
    54           2              2           0     
    55           2              2           0     
(dbt-pyvenv) [biery@mu2edaq13 rundir]$ hdf5_dump.py -p trigger -f swtest_run42830909_0001_biery_20210428T141000.hdf5 | grep 'Trigger number'
Trigger number                : 57
Trigger number                : 58
Trigger number                : 59
Trigger number                : 60
Trigger number                : 61
Trigger number                : 62
Trigger number                : 63
Trigger number                : 64
Trigger number                : 65
Trigger number                : 66
Trigger number                : 67
Trigger number                : 68
Trigger number                : 69
Trigger number                : 70
Trigger number                : 71
Trigger number                : 72
Trigger number                : 73
Trigger number                : 74
Trigger number                : 75
Trigger number                : 76
Trigger number                : 77
Trigger number                : 78
Trigger number                : 79
Trigger number                : 80
Trigger number                : 81
Trigger number                : 82
Trigger number                : 83
Trigger number                : 84
Trigger number                : 85
Trigger number                : 86
Trigger number                : 87
Trigger number                : 88
Trigger number                : 89
Trigger number                : 90
Trigger number                : 91
Trigger number                : 92
Trigger number                : 93
Trigger number                : 94
Trigger number                : 95
Trigger number                : 96
Trigger number                : 97
Trigger number                : 98
Trigger number                : 99
Trigger number                : 100
Trigger number                : 101
Trigger number                : 102
Trigger number                : 103
Trigger number                : 104
Trigger number                : 105
Trigger number                : 106
Trigger number                : 107
Trigger number                : 108
Trigger number                : 109
Trigger number                : 110
Trigger number                : 111
Trigger number                : 112

**Comment by dingp** [comment]
Yeah, the current "record number" is indexed from 0 internally to the data file. I will change it to the real trigger number later today.
