### ISSUE TITLE
`DataWriter` accesses past the end of `Fragment`

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/dfmodules#9]
The hex-dumping loop beginning here:

https://github.com/DUNE-DAQ/dfmodules/blob/29184234355e45cd4ae905f4dcb9b3d2236e0f5c/plugins/DataWriter.cpp#L152

doesn't check the fragment size, so it accesses past-the-end if the fragment is small (below 20 bytes?).

**Comment by philiprodrigues** [comment]
My initial description was incorrect, because the dump starts at `Fragment::get_storage_location()`, which is the start of the header, not the start of the payload, so the loop prints out the header. But there might still be a minor problem, since it's printing `20*sizeof(uint32_t) = 80` bytes, but `sizeof(FragmentHeader)=72`

**Comment by bieryAtFnal** [comment]
I've started working on a fix for this on a bugfix branch...

**Comment by bieryAtFnal** [comment]
I believe that this issue was fixed for minidaqapp v1.0, so I'm going to close this Issue.
